###############################################################################
#                        Author: james.li0122@gmail.com                       #
###############################################################################
version: '3.7'

services:
  base_image:
    build: .
    image: cicada_ci:dev

  dev_webclient:
    image: cicada_ci:dev
    command: ['/bin/bash', '-c', 'cd webclient && npm run serve']
    depends_on:
      - base_image
    restart: on-failure
    #volumes为debug功能，可注释掉，开启情况下能支持热更新，但会增加host机器cpu占用
    volumes:
      - ./webclient/src:/usr/app/webclient/src

  dev_webserver:
    image: cicada_ci:dev
    command: ['/bin/bash', '-c', 'cd webserver && npm run start:dev']
    ports:
      - 3600:3600
    depends_on:
      - base_image
      - dev_mysql
    environment:
      DATABASE_HOST: dev_mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: db_feci_open
      DEV_CLIENT_HOST: dev_webclient
    restart: on-failure
    #volumes为debug功能，可注释掉，开启情况下能支持热更新，但会增加host机器cpu占用
    volumes:
      - ./webserver/src:/usr/app/webserver/src

  dev_ciserver:
    image: cicada_ci:dev
    command: ['/bin/bash', '-c', 'cd ciserver && npm run start:dev']
    depends_on:
      - base_image
      - dev_mysql
      - dev_redis
    environment:
      DATABASE_HOST: dev_mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: db_feci_open
      REDIS_HOST: dev_redis
    ports:
      - 3700:3700
    restart: on-failure
    #volumes为debug功能，可注释掉，开启情况下能支持热更新，但会增加host机器cpu占用
    volumes:
      - ./ciserver/src:/usr/app/ciserver/src

  dev_redis:
    image: 'redis:alpine'
    command: redis-server
    volumes:
      - ./.docker/redis_data:/var/lib/redis

  dev_mysql:
    image: mysql:5.7
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
      ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: db_feci_open
    volumes:
      - ./.docker/mysql_data:/var/lib/mysql

  dev_mysql_adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
